name: Package to Nuget

on:
  push:
    branches:
      - master

jobs:
  pack:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish to Nuget
      env: 
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
      run: |
        dotnet pack template/BootstrapBlazorServerPack.csproj -c Release -o publish
        dotnet nuget push publish/Bootstrap.Blazor.Templates.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
